services:
  - type: web
    name: happy-birthday-ngoc-mai
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
